import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY!);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

export async function sendMessageToGemini(message: string): Promise<string> {
  const prompt = `Bạn là một AI ChatBot của 1 trang web, chuyên trả lời những câu hỏi về Quan điểm cơ bản của chủ nghĩa Mác-Lênin về giai cấp công nhân và sứ mệnh lịch sử của giai cấp công nhân. Đây là tài liệu liên quan đến nội dung của web mà bạn sẽ dựa vào để trả lời câu hỏi:

	4. Thời kỳ từ ngày 4-2-1930 đến ngày 28-1-1941: Vượt qua thử thách, giữ vững đường lối, phương pháp cách mạng Việt Nam đúng đắn, sáng tạo:
	Những thử thách lớn với Hồ Chí Minh xuất hiện không chỉ từ phía kẻ thù, mà còn từ trong nội bộ những người cách mạng. Một số người trong Quốc tế Cộng sản và Đảng Cộng sản Việt Nam có những nhìn nhận sai lầm về Hồ Chí Minh do chịu ảnh hưởng quan điểm giáo điều tả khuynh xuất hiện trong Đại hội VI của Quốc tế Cộng sản. Do không nắm vững tình hình các dân tộc thuộc địa và ở Đông Dương, nên tư tưởng mới mẻ, đúng đắn, sáng tạo của Hồ Chí Minh trong Cương lĩnh chính trị đầu tiên chẳng những không được hiểu và chấp nhận mà còn bị họ phê phán, bị coi là "hữu khuynh", "dân tộc chủ nghĩa".
	Hội nghị Trung ương Đảng họp tháng 10-1930 ra nghị quyết cho rằng: Hội nghị hiệp nhất Đảng do Nguyễn Ái Quốc chủ trì có nhiều sai lầm, "chỉ lo đến việc phản đế mà quên mất lợi ích giai cấp tranh đấu, ấy là một sự rất nguy hiểm"; việc phân chia thành trung, tiểu, đại địa chủ trong sách lược của Đảng là không đúng. Hội nghị ra án nghị quyết: "Thủ tiêu chánh cương, sách lược và điều lệ Đảng"; bỏ tên Đảng Cộng sản Việt Nam do Hồ Chí Minh và những người tham gia Hội nghị thành lập Đảng xác định, lấy tên là Đảng Cộng sản Đông Dương, hoạt động theo như chỉ thị của Quốc tế Cộng sản, v.v.
	Thoát khỏi nhà tù của thực dân Anh ở Hồng Kông, năm 1934, Hồ Chí Minh trở lại Liên Xô, vào học Trường Quốc tế Lênin. Sau đó, Người làm nghiên cứu sinh tại Ban Sử của Viện Nghiên cứu các vấn đề dân tộc và thuộc địa của Quốc tế Cộng sản. Trong quãng thời gian từ năm 1934 đến năm 1938, Hồ Chí Minh vẫn còn bị hiểu lầm về một số hoạt động thực tế và quan điểm cách mạng.
	Khi Chiến tranh thế giới thứ hai bùng nổ, nhận thấy thời cuộc sẽ có những chuyển biến lớn, nên cần phải trở về nước trực tiếp tham gia lãnh đạo cách mạng Việt Nam, ngày 6-6-1938, Hồ Chí Minh gửi thư cho một lãnh đạo Quốc tế Cộng sản, đề nghị cho phép trở về nước hoạt động, trong đó, có đoạn viết:
	"Xin đồng chí giúp đỡ tôi thay đổi tình cảnh đau buồn này... Đừng để tôi sống quá lâu trong tình trạng không hoạt động và giống như là sống ở bên cạnh, ở bên ngoài của Đảng". Đề nghị này được chấp nhận.
	Tháng 10-1938, Hồ Chí Minh rời Liên Xô, đi qua Trung Quốc để trở về Việt Nam. Tháng 12-1940, Hồ Chí Minh về gần biên giới Việt Nam – Trung Quốc, liên lạc với Trung ương Đảng Cộng sản Đông Dương, trực tiếp chỉ đạo cách mạng Việt Nam. Người mở lớp huấn luyện cán bộ, viết sách: Con đường giải phóng, trong đó nêu ra phương pháp cách mạng giành chính quyền (1-1941).
	Tư tưởng Hồ Chí Minh được Đảng Cộng sản Đông Dương khẳng định, trở thành thành yếu tố chỉ đạo cách mạng Việt Nam từ Hội nghị Trung ương Đảng tháng 5- 1941. Cuối tháng 1-1941, Hồ Chí Minh về nước. Tháng 5-1941, tại Pác Bó (huyện Hà Quảng, tỉnh Cao Bằng), với tư cách cán bộ Quốc tế Cộng sản, Người chủ trì Hội nghị Ban Chấp hành Trung ương Đảng. Hội nghị này đã đặt nhiệm vụ giải phóng dân tộc lên hàng đầu. Người khẳng định rõ: "Trong lúc này quyền lợi dân tộc giải phóng cao hơn hết thảy. Chúng ta phải đoàn kết lại đánh đổ bọn đế quốc và bọn Việt gian đặng cứu giống nòi ra khỏi nước sôi lửa nóng"2.
	Nghị quyết của Hội nghị Trung ương Đảng nêu rõ: "Trong lúc này quyền lợi của bộ phận, của giai cấp phải đặt dưới sự sinh tử, tồn vong của quốc gia, của dân tộc. Trong lúc này, nếu không giải quyết được vấn đề dân tộc giải phóng, không đòi được độc lập, tự do cho toàn thể dân tộc, thì chẳng những toàn thể quốc gia dân tộc còn chịu mãi kiếp ngựa trâu, mà quyền lợi của bộ phận, giai cấp đến vạn năm cũng không đòi lại được".
	Hội nghị Trung ương Đảng đã tạm thời gác lại khẩu hiệu cách mạng điền địa, xóa bỏ vấn đề lập Chính phủ Liên bang Cộng hoà dân chủ Đông Dương, thay vào đó là chủ trương sẽ thành lập Chính phủ nhân dân của nước Việt Nam Dân chủ Cộng hoà, nêu chủ trương lập Mặt trận Việt Minh, thực hiện đại đoàn kết dân tộc trên cơ sở nòng cốt liên minh công nông, nêu ra phương hướng khởi nghĩa vũ trang giành chính quyền, V.V...
	Nghị quyết Hội nghị Trung ương Đảng tháng 5-1941 đã hoàn chỉnh thêm một bước sự chuyển hướng chiến lược và sách lược của cách mạng Việt Nam được vạch ra từ Hội nghị Trung ương Đảng tháng 11-1939. Sự chuyển hướng được vạch ra từ hai cuộc Hội nghị này thực chất là sự trở về với quan điểm của Hồ Chí Minh đã nêu ra từ trong Cương lĩnh chính trị đầu tiên của Đảng khi thành lập Đảng Cộng sản Việt Nam đầu năm 1930.
	Trải qua sóng gió, thử thách, những quan điểm cơ bản nhất về đường lối cách mạng giải phóng dân tộc Việt Nam của Hồ Chí Minh được Đảng khẳng định đưa vào thực tiễn tổ chức nhân dân biến thành các phong trào cách mạng để dẫn tới thắng lợi của cuộc Cách mạng Tháng Tám năm 1945.

  5. Thời kỳ từ ngày 29-1-1941 đến ngày 2-9-1969: Tư tưởng Hồ Chí Minh tiếp tục phát triển, soi đường cho sự nghiệp cách mạng của Đảng và nhân dân ta
	Trong thời kỳ này, tư tưởng Hồ Chí Minh và đường lối của Đảng cơ bản là thống nhất. Trong những lần làm việc với với cán bộ, đảng viên, nhân dân các địa phương, ban, bộ, ngành, Hồ Chí Minh nhiều lần đưa ra những quan điểm sáng tạo, đi trước thời gian, càng ngày càng được Đảng ta làm sáng tỏ và tiếp tục phát triển soi sáng con đường cách mạng Việt Nam.
	Ngày 19-5-1941, Hồ Chí Minh sáng lập Mặt trận Việt Minh; ngày 22-12-1944, sáng lập Việt Nam tuyên truyền giải phóng quân, tiền thân của Quân đội nhân dân Việt Nam. Ngày 18-8-1945, chớp đúng thời cơ, Hồ Chí Minh ra Lời kêu gọi Tổng khởi nghĩa giành chính quyền. Cách mạng Tháng Tám năm 1945 thành công lật đổ chế độ phong kiến hơn ngàn năm, lật đổ ách thống trị của thực dân Pháp hơn 80 năm và giành lại độc lập dân tộc trực tiếp từ tay phát xít Nhật. Đây là thắng lợi to lớn đầu tiên của chủ nghĩa Mác - Lênin và tư tưởng Hồ Chí Minh ở Việt Nam.
	Ngày 2-9-1945, Hồ Chí Minh đọc Tuyên ngôn Độc lập. Nước Việt Nam Dân chủ Cộng hoà ra đời, mở ra một kỷ nguyên mới trong lịch sử dân tộc Việt Nam – kỷ nguyên độc lập dân tộc gắn liền với chủ nghĩa xã hội.
	Từ ngày 2-9-1945 đến ngày 19-12-1946, Hồ Chí Minh đề ra chiến lược sách lược cách mạng sáng suốt, lãnh đạo Đảng và chính quyền cách mạng non trẻ trải qua thử thách ngàn cân treo sợi tóc. Với phương châm Dĩ bất biến ứng vạn biến, giữ vững mục tiêu đấu tranh cho chủ quyền độc lập dân tộc, tự do, ấm no, hạnh phúc cho nhân dân bằng các sách lược cách mạng linh hoạt, mềm dẻo. Người đã chỉ đạo thành công sách lược: Khi thì tạm hoà hoãn với Tưởng để rảnh tay đối phó với thực dân Pháp, lúc thì tạm hoà hoãn với Pháp để đuổi quân Tưởng và quét sạch bọn phản động tay sai của Tưởng về nước, giành thời gian củng cố lực lượng, chuẩn bị toàn quốc kháng chiến chống thực dân Pháp. Những biện pháp sáng suốt đó đã được ghi vào lịch sử cách mạng Việt Nam như một mẫu mực tuyệt vời của sách lược lợi dụng mâu thuẫn trong hàng ngũ kẻ thù và sự nhân nhượng có nguyên tắc; thêm bạn bớt thù, xây dựng khối đại đoàn kết dân tộc vững chắc.
	Từ năm 1946 đến năm 1954, Hồ Chí Minh là linh hồn của cuộc kháng chiến chống thực dân Pháp. Đảng, do Người làm lãnh tụ, đã đề ra đường lối kháng chiến lâu dài, toàn dân, toàn diện, tự lực cánh sinh. Đồng thời, Người lãnh đạo, tổ chức, chỉ đạo kháng chiến chống thực dân Pháp. Lời kêu gọi toàn quốc kháng chiến của Hồ Chí Minh ngày 19-12-1946 vừa thể hiện khái quát đường lối kháng chiến chống thực dân Pháp, vừa là lời thề thiêng liêng liêng bảo vệ Tổ quốc của dân tộc Việt Nam, với ý chí, quyết tâm thà hy sinh tất cả chứ không chịu mất nước, nhất định không chịu làm nô lệ.
	Trong thời kỳ này, Hồ Chí Minh hoàn thiện lý luận cách mạng dân tộc dân chủ nhân dân, và từng bước hình thành tư tưởng về xây dựng chủ nghĩa xã hội ở Việt Nam. Năm 1954, cuộc kháng chiến chống thực dân pháp ở Việt Nam thắng lợi, mở ra thời kỳ sụp đổ của hệ thống thuộc địa kiểu cũ trên phạm vi toàn thế giới. Hòa bình lập lại ở miền Bắc Việt Nam; và miền Bắc bắt đầu bước vào thời kỳ quá độ lên chủ nghĩa xã hội.
	Từ năm 1954 đến năm 1969, Hồ Chí Minh xác định và lãnh đạo thực hiện đường lối cùng một lúc thi hành hai nhiệm vụ chiến lược của cách mạng Việt Nam: Xây dựng chủ nghĩa xã hội ở miền Bắc; tiếp tục cuộc cách mạng dân tộc dân chủ nhân dân ở miền Nam. Tất cả nhằm giành được hòa bình, độc lập, thống nhất nước nhà.
	Trong thời kỳ này, Hồ Chí Minh bổ sung hoàn thiện hệ thống quan điểm cơ bản của cách mạng Việt Nam trên tất cả các lĩnh vực chính trị, kinh tế, quân sự, văn hoá, đạo đức, đối ngoại, v,v...nhằm hướng tới mục tiêu nước ta được hoàn toàn độc lập, dân ta được hoàn toàn tự do, dân chủ, xây dựng thành công chủ nghĩa xã hội.
	Trong những giờ phút gay go nhất của cuộc kháng chiến chống Mỹ, cứu nước, khi đế quốc Mỹ tăng cường quân đội viễn chinh Mỹ vào miền Nam và đẩy mạnh đánh phá miền Bắc bằng không quân và hải quân Mỹ, ngày 17-7-1966, Hồ Chí Minh ra Lời kêu gọi đồng bào và chiến sĩ cả nước. Trong đó, nêu ra một chân lý lớn của thời đại: Không có gì quý hơn độc lập, tự do. Người khẳng định nhân dân Việt Nam chẳng những không sợ, mà còn quyết tâm đánh thắng giặc Mỹ xâm lược. "Đến ngày thắng lợi, nhân dân ta sẽ xây dựng lại đất nước ta đàng hoàng hơn, to đẹp hơn!"
	Trước khi đi xa, Người để lại Di chúc, một văn kiện lịch sử vô giá, kết tinh tư tưởng, trí tuệ, tâm hồn, đạo đức, phong cách của một lãnh tụ cách mạng, anh hùng dân tộc vĩ đại, nhà tư tưởng lỗi lạc, nhà văn hóa kiệt xuất, suốt đời vì dân, vì nước. Điều mong muốn cuối cùng của Hồ Chí Minh là: “Toàn Đảng, toàn dân ta đoàn kết phấn đấu, xây dựng một nước Việt Nam hoà bình, thống nhất, độc lập, dân chủ và giàu mạnh, và góp phần xứng đáng vào sự nghiệp cách mạng thế giới".
	Tư tưởng Hồ Chí Minh tiếp tục được Đảng Cộng sản Việt Nam vận dụng và phát triển trong thực tiễn cách mạng Việt Nam. Đảng Cộng sản Việt Nam đã tiếp tục lãnh đạo miền Bắc xây dựng chủ nghĩa xã hội, miền Nam tiếp tục thực hiện cuộc cách mạng dân tộc dân chủ nhân dân đi đến thắng lợi hoàn toàn. Từ năm 1975, cả nước hòa bình, độc lập, thống nhất đi lên chủ nghĩa xã hội. Ngày nay, Đảng Cộng sản Việt Nam đang đưa sự nghiệp đổi mới vững bước đi lên.

	Thông tin thêm: Năm 1923, nhà thơ, nhà báo nổi tiếng người Xô Viết O.Mandenxtam gặp Nguyễn Ái Quốc lúc này 33 tuổi ở Moskva, O.Mandenxtam đã đánh giá Nguyễn Ái Quốc là một người phương Đông lịch sự, là biểu hiện cho một nền văn hóa của tương lai: “Từ Nguyễn Ái Quốc tỏa ra một thứ văn hóa, không phải văn hóa châu Âu, mà có lẽ là một nền văn hóa của tương lai. Từ trong giọng nói đầm ấm, thanh cao của Người, chúng ta như nghe thấy ngày mai, như thấy viễn cảnh trời yên biển lặng của tình hữu ái bao la toàn thế giới mênh mang như nước đại dương”.
	
	Đây là câu hỏi của 1 người ghé thăm web mà bạn cần trả lời: ${message}
	Nếu câu hỏi không liên quan đến tài liệu hoặc nội dung mà bạn cần trả lời thì hãy nói "Câu hỏi của bạn không liên quan đến đề tài của trang web này, bạn có thể tìm hiểu thêm thông qua các nguồn khác như Google"`;
  const result = await model.generateContent(prompt);
  return result.response.text();
}

export async function sendContentToGenerateQuizGemini(): Promise<string> {
  const prompt = `Bạn là một AI tạo Quiz cho website học tập về chủ nghĩa Mác-Lênin. 
  Hãy tạo ra 5 câu hỏi trắc nghiệm (tiếng Việt) liên quan đến chủ đề:
  "Quan điểm cơ bản của chủ nghĩa Mác-Lênin về giai cấp công nhân và sứ mệnh lịch sử của giai cấp công nhân"
  và gắn với tư tưởng Hồ Chí Minh trong từng giai đoạn cách mạng.
  Liên quan đến nội dung
  4. Thời kỳ từ ngày 4-2-1930 đến ngày 28-1-1941: Vượt qua thử thách, giữ vững đường lối, phương pháp cách mạng Việt Nam đúng đắn, sáng tạo:
	Những thử thách lớn với Hồ Chí Minh xuất hiện không chỉ từ phía kẻ thù, mà còn từ trong nội bộ những người cách mạng. Một số người trong Quốc tế Cộng sản và Đảng Cộng sản Việt Nam có những nhìn nhận sai lầm về Hồ Chí Minh do chịu ảnh hưởng quan điểm giáo điều tả khuynh xuất hiện trong Đại hội VI của Quốc tế Cộng sản. Do không nắm vững tình hình các dân tộc thuộc địa và ở Đông Dương, nên tư tưởng mới mẻ, đúng đắn, sáng tạo của Hồ Chí Minh trong Cương lĩnh chính trị đầu tiên chẳng những không được hiểu và chấp nhận mà còn bị họ phê phán, bị coi là "hữu khuynh", "dân tộc chủ nghĩa".
	Hội nghị Trung ương Đảng họp tháng 10-1930 ra nghị quyết cho rằng: Hội nghị hiệp nhất Đảng do Nguyễn Ái Quốc chủ trì có nhiều sai lầm, "chỉ lo đến việc phản đế mà quên mất lợi ích giai cấp tranh đấu, ấy là một sự rất nguy hiểm"; việc phân chia thành trung, tiểu, đại địa chủ trong sách lược của Đảng là không đúng. Hội nghị ra án nghị quyết: "Thủ tiêu chánh cương, sách lược và điều lệ Đảng"; bỏ tên Đảng Cộng sản Việt Nam do Hồ Chí Minh và những người tham gia Hội nghị thành lập Đảng xác định, lấy tên là Đảng Cộng sản Đông Dương, hoạt động theo như chỉ thị của Quốc tế Cộng sản, v.v.
	Thoát khỏi nhà tù của thực dân Anh ở Hồng Kông, năm 1934, Hồ Chí Minh trở lại Liên Xô, vào học Trường Quốc tế Lênin. Sau đó, Người làm nghiên cứu sinh tại Ban Sử của Viện Nghiên cứu các vấn đề dân tộc và thuộc địa của Quốc tế Cộng sản. Trong quãng thời gian từ năm 1934 đến năm 1938, Hồ Chí Minh vẫn còn bị hiểu lầm về một số hoạt động thực tế và quan điểm cách mạng.
	Khi Chiến tranh thế giới thứ hai bùng nổ, nhận thấy thời cuộc sẽ có những chuyển biến lớn, nên cần phải trở về nước trực tiếp tham gia lãnh đạo cách mạng Việt Nam, ngày 6-6-1938, Hồ Chí Minh gửi thư cho một lãnh đạo Quốc tế Cộng sản, đề nghị cho phép trở về nước hoạt động, trong đó, có đoạn viết:
	"Xin đồng chí giúp đỡ tôi thay đổi tình cảnh đau buồn này... Đừng để tôi sống quá lâu trong tình trạng không hoạt động và giống như là sống ở bên cạnh, ở bên ngoài của Đảng". Đề nghị này được chấp nhận.
	Tháng 10-1938, Hồ Chí Minh rời Liên Xô, đi qua Trung Quốc để trở về Việt Nam. Tháng 12-1940, Hồ Chí Minh về gần biên giới Việt Nam – Trung Quốc, liên lạc với Trung ương Đảng Cộng sản Đông Dương, trực tiếp chỉ đạo cách mạng Việt Nam. Người mở lớp huấn luyện cán bộ, viết sách: Con đường giải phóng, trong đó nêu ra phương pháp cách mạng giành chính quyền (1-1941).
	Tư tưởng Hồ Chí Minh được Đảng Cộng sản Đông Dương khẳng định, trở thành thành yếu tố chỉ đạo cách mạng Việt Nam từ Hội nghị Trung ương Đảng tháng 5- 1941. Cuối tháng 1-1941, Hồ Chí Minh về nước. Tháng 5-1941, tại Pác Bó (huyện Hà Quảng, tỉnh Cao Bằng), với tư cách cán bộ Quốc tế Cộng sản, Người chủ trì Hội nghị Ban Chấp hành Trung ương Đảng. Hội nghị này đã đặt nhiệm vụ giải phóng dân tộc lên hàng đầu. Người khẳng định rõ: "Trong lúc này quyền lợi dân tộc giải phóng cao hơn hết thảy. Chúng ta phải đoàn kết lại đánh đổ bọn đế quốc và bọn Việt gian đặng cứu giống nòi ra khỏi nước sôi lửa nóng"2.
	Nghị quyết của Hội nghị Trung ương Đảng nêu rõ: "Trong lúc này quyền lợi của bộ phận, của giai cấp phải đặt dưới sự sinh tử, tồn vong của quốc gia, của dân tộc. Trong lúc này, nếu không giải quyết được vấn đề dân tộc giải phóng, không đòi được độc lập, tự do cho toàn thể dân tộc, thì chẳng những toàn thể quốc gia dân tộc còn chịu mãi kiếp ngựa trâu, mà quyền lợi của bộ phận, giai cấp đến vạn năm cũng không đòi lại được".
	Hội nghị Trung ương Đảng đã tạm thời gác lại khẩu hiệu cách mạng điền địa, xóa bỏ vấn đề lập Chính phủ Liên bang Cộng hoà dân chủ Đông Dương, thay vào đó là chủ trương sẽ thành lập Chính phủ nhân dân của nước Việt Nam Dân chủ Cộng hoà, nêu chủ trương lập Mặt trận Việt Minh, thực hiện đại đoàn kết dân tộc trên cơ sở nòng cốt liên minh công nông, nêu ra phương hướng khởi nghĩa vũ trang giành chính quyền, V.V...
	Nghị quyết Hội nghị Trung ương Đảng tháng 5-1941 đã hoàn chỉnh thêm một bước sự chuyển hướng chiến lược và sách lược của cách mạng Việt Nam được vạch ra từ Hội nghị Trung ương Đảng tháng 11-1939. Sự chuyển hướng được vạch ra từ hai cuộc Hội nghị này thực chất là sự trở về với quan điểm của Hồ Chí Minh đã nêu ra từ trong Cương lĩnh chính trị đầu tiên của Đảng khi thành lập Đảng Cộng sản Việt Nam đầu năm 1930.
	Trải qua sóng gió, thử thách, những quan điểm cơ bản nhất về đường lối cách mạng giải phóng dân tộc Việt Nam của Hồ Chí Minh được Đảng khẳng định đưa vào thực tiễn tổ chức nhân dân biến thành các phong trào cách mạng để dẫn tới thắng lợi của cuộc Cách mạng Tháng Tám năm 1945.

  5. Thời kỳ từ ngày 29-1-1941 đến ngày 2-9-1969: Tư tưởng Hồ Chí Minh tiếp tục phát triển, soi đường cho sự nghiệp cách mạng của Đảng và nhân dân ta
	Trong thời kỳ này, tư tưởng Hồ Chí Minh và đường lối của Đảng cơ bản là thống nhất. Trong những lần làm việc với với cán bộ, đảng viên, nhân dân các địa phương, ban, bộ, ngành, Hồ Chí Minh nhiều lần đưa ra những quan điểm sáng tạo, đi trước thời gian, càng ngày càng được Đảng ta làm sáng tỏ và tiếp tục phát triển soi sáng con đường cách mạng Việt Nam.
	Ngày 19-5-1941, Hồ Chí Minh sáng lập Mặt trận Việt Minh; ngày 22-12-1944, sáng lập Việt Nam tuyên truyền giải phóng quân, tiền thân của Quân đội nhân dân Việt Nam. Ngày 18-8-1945, chớp đúng thời cơ, Hồ Chí Minh ra Lời kêu gọi Tổng khởi nghĩa giành chính quyền. Cách mạng Tháng Tám năm 1945 thành công lật đổ chế độ phong kiến hơn ngàn năm, lật đổ ách thống trị của thực dân Pháp hơn 80 năm và giành lại độc lập dân tộc trực tiếp từ tay phát xít Nhật. Đây là thắng lợi to lớn đầu tiên của chủ nghĩa Mác - Lênin và tư tưởng Hồ Chí Minh ở Việt Nam.
	Ngày 2-9-1945, Hồ Chí Minh đọc Tuyên ngôn Độc lập. Nước Việt Nam Dân chủ Cộng hoà ra đời, mở ra một kỷ nguyên mới trong lịch sử dân tộc Việt Nam – kỷ nguyên độc lập dân tộc gắn liền với chủ nghĩa xã hội.
	Từ ngày 2-9-1945 đến ngày 19-12-1946, Hồ Chí Minh đề ra chiến lược sách lược cách mạng sáng suốt, lãnh đạo Đảng và chính quyền cách mạng non trẻ trải qua thử thách ngàn cân treo sợi tóc. Với phương châm Dĩ bất biến ứng vạn biến, giữ vững mục tiêu đấu tranh cho chủ quyền độc lập dân tộc, tự do, ấm no, hạnh phúc cho nhân dân bằng các sách lược cách mạng linh hoạt, mềm dẻo. Người đã chỉ đạo thành công sách lược: Khi thì tạm hoà hoãn với Tưởng để rảnh tay đối phó với thực dân Pháp, lúc thì tạm hoà hoãn với Pháp để đuổi quân Tưởng và quét sạch bọn phản động tay sai của Tưởng về nước, giành thời gian củng cố lực lượng, chuẩn bị toàn quốc kháng chiến chống thực dân Pháp. Những biện pháp sáng suốt đó đã được ghi vào lịch sử cách mạng Việt Nam như một mẫu mực tuyệt vời của sách lược lợi dụng mâu thuẫn trong hàng ngũ kẻ thù và sự nhân nhượng có nguyên tắc; thêm bạn bớt thù, xây dựng khối đại đoàn kết dân tộc vững chắc.
	Từ năm 1946 đến năm 1954, Hồ Chí Minh là linh hồn của cuộc kháng chiến chống thực dân Pháp. Đảng, do Người làm lãnh tụ, đã đề ra đường lối kháng chiến lâu dài, toàn dân, toàn diện, tự lực cánh sinh. Đồng thời, Người lãnh đạo, tổ chức, chỉ đạo kháng chiến chống thực dân Pháp. Lời kêu gọi toàn quốc kháng chiến của Hồ Chí Minh ngày 19-12-1946 vừa thể hiện khái quát đường lối kháng chiến chống thực dân Pháp, vừa là lời thề thiêng liêng liêng bảo vệ Tổ quốc của dân tộc Việt Nam, với ý chí, quyết tâm thà hy sinh tất cả chứ không chịu mất nước, nhất định không chịu làm nô lệ.
	Trong thời kỳ này, Hồ Chí Minh hoàn thiện lý luận cách mạng dân tộc dân chủ nhân dân, và từng bước hình thành tư tưởng về xây dựng chủ nghĩa xã hội ở Việt Nam. Năm 1954, cuộc kháng chiến chống thực dân pháp ở Việt Nam thắng lợi, mở ra thời kỳ sụp đổ của hệ thống thuộc địa kiểu cũ trên phạm vi toàn thế giới. Hòa bình lập lại ở miền Bắc Việt Nam; và miền Bắc bắt đầu bước vào thời kỳ quá độ lên chủ nghĩa xã hội.
	Từ năm 1954 đến năm 1969, Hồ Chí Minh xác định và lãnh đạo thực hiện đường lối cùng một lúc thi hành hai nhiệm vụ chiến lược của cách mạng Việt Nam: Xây dựng chủ nghĩa xã hội ở miền Bắc; tiếp tục cuộc cách mạng dân tộc dân chủ nhân dân ở miền Nam. Tất cả nhằm giành được hòa bình, độc lập, thống nhất nước nhà.
	Trong thời kỳ này, Hồ Chí Minh bổ sung hoàn thiện hệ thống quan điểm cơ bản của cách mạng Việt Nam trên tất cả các lĩnh vực chính trị, kinh tế, quân sự, văn hoá, đạo đức, đối ngoại, v,v...nhằm hướng tới mục tiêu nước ta được hoàn toàn độc lập, dân ta được hoàn toàn tự do, dân chủ, xây dựng thành công chủ nghĩa xã hội.
	Trong những giờ phút gay go nhất của cuộc kháng chiến chống Mỹ, cứu nước, khi đế quốc Mỹ tăng cường quân đội viễn chinh Mỹ vào miền Nam và đẩy mạnh đánh phá miền Bắc bằng không quân và hải quân Mỹ, ngày 17-7-1966, Hồ Chí Minh ra Lời kêu gọi đồng bào và chiến sĩ cả nước. Trong đó, nêu ra một chân lý lớn của thời đại: Không có gì quý hơn độc lập, tự do. Người khẳng định nhân dân Việt Nam chẳng những không sợ, mà còn quyết tâm đánh thắng giặc Mỹ xâm lược. "Đến ngày thắng lợi, nhân dân ta sẽ xây dựng lại đất nước ta đàng hoàng hơn, to đẹp hơn!"
	Trước khi đi xa, Người để lại Di chúc, một văn kiện lịch sử vô giá, kết tinh tư tưởng, trí tuệ, tâm hồn, đạo đức, phong cách của một lãnh tụ cách mạng, anh hùng dân tộc vĩ đại, nhà tư tưởng lỗi lạc, nhà văn hóa kiệt xuất, suốt đời vì dân, vì nước. Điều mong muốn cuối cùng của Hồ Chí Minh là: “Toàn Đảng, toàn dân ta đoàn kết phấn đấu, xây dựng một nước Việt Nam hoà bình, thống nhất, độc lập, dân chủ và giàu mạnh, và góp phần xứng đáng vào sự nghiệp cách mạng thế giới".
	Tư tưởng Hồ Chí Minh tiếp tục được Đảng Cộng sản Việt Nam vận dụng và phát triển trong thực tiễn cách mạng Việt Nam. Đảng Cộng sản Việt Nam đã tiếp tục lãnh đạo miền Bắc xây dựng chủ nghĩa xã hội, miền Nam tiếp tục thực hiện cuộc cách mạng dân tộc dân chủ nhân dân đi đến thắng lợi hoàn toàn. Từ năm 1975, cả nước hòa bình, độc lập, thống nhất đi lên chủ nghĩa xã hội. Ngày nay, Đảng Cộng sản Việt Nam đang đưa sự nghiệp đổi mới vững bước đi lên.

  ⚠️ Yêu cầu:
  - Trả về kết quả duy nhất ở dạng JSON, không có bất kỳ giải thích hay mô tả nào bên ngoài.
  - Mỗi phần tử trong mảng JSON gồm:
	{
	  "question": "Câu hỏi ...",
	  "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
	  "answer": "A"
	}
  - Đáp án chỉ ghi ký tự "A", "B", "C", hoặc "D" tương ứng với lựa chọn đúng.
  
  Bắt đầu trả về ngay JSON của 5 câu hỏi.`;

  const result = await model.generateContent(prompt);
  return cleanGeminiJsonResponse(result.response.text());
}
export function cleanGeminiJsonResponse(response: string): string {
  // Cắt khoảng trắng đầu cuối
  let cleaned = response.trim();

  // Nếu có bọc trong ```json ... ``` thì loại bỏ
  if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```[a-zA-Z]*\n?/, ""); // bỏ ```json hoặc ```
    cleaned = cleaned.replace(/```$/, ""); // bỏ ```
  }

  // Cắt tiếp khoảng trắng dư thừa
  return cleaned.trim();
}
